DATASPINE_MODEL_NAME={{ DATASPINE_MODEL_NAME }} \
DATASPINE_MODEL_TAG={{ DATASPINE_MODEL_TAG }} \
DATASPINE_MODEL_TYPE={{ DATASPINE_MODEL_TYPE }} \
DATASPINE_MODEL_RUNTIME={{ DATASPINE_MODEL_RUNTIME }} \
DATASPINE_MODEL_CHIP={{ DATASPINE_MODEL_CHIP }} \
DATASPINE_INPUT_PATH={{ DATASPINE_INPUT_PATH }} \
DATASPINE_OUTPUT_PATH={{ DATASPINE_OUTPUT_PATH }} \
  python dataspine_predict.py
